# Generated by Django 5.1.4 on 2025-01-25 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='posr',
            new_name='post',
        ),
    ]
